---@class Nightshade
---@field config NightshadeConfig
---@field palette NightshadePalette
local Nightshade = {}

---@class ItalicConfig
---@field strings boolean
---@field comments boolean
---@field operators boolean
---@field folds boolean
---@field emphasis boolean

---@class HighlightDefinition
---@field fg string?
---@field bg string?
---@field sp string?
---@field blend integer?
---@field bold boolean?
---@field standout boolean?
---@field underline boolean?
---@field undercurl boolean?
---@field underdouble boolean?
---@field underdotted boolean?
---@field strikethrough boolean?
---@field italic boolean?
---@field reverse boolean?
---@field nocombine boolean?

---@class NightshadeConfig
---@field bold boolean?
---@field dim_inactive boolean?
---@field inverse boolean?
---@field invert_selection boolean?
---@field invert_signs boolean?
---@field invert_tabline boolean?
---@field italic ItalicConfig?
---@field overrides table<string, HighlightDefinition>?
---@field palette_overrides table<string, string>?
---@field strikethrough boolean?
---@field terminal_colors boolean?
---@field transparent_mode boolean?
---@field undercurl boolean?
---@field underline boolean?
local default_config = {
    terminal_colors = true,
    undercurl = true,
    underline = true,
    bold = true,
    italic = {
        strings = true,
        emphasis = true,
        comments = true,
        operators = false,
        folds = true,
    },
    strikethrough = true,
    invert_selection = false,
    invert_signs = false,
    invert_tabline = false,
    inverse = true,
    contrast = "",
    palette_overrides = {},
    overrides = {},
    dim_inactive = false,
    transparent_mode = false,
}

Nightshade.config = vim.deepcopy(default_config)

-- main gruvbox color palette
---@class NightshadePalette
Nightshade.palette = {
    dark0 = "#0f1612",
    dark1 = "#232a23",
    dark2 = "#393f35",
    dark3 = "#505547",
    dark4 = "#686c5b",
    light0 = "#eeeac6",
    light1 = "#d2cfaf",
    light2 = "#b6b599",
    light3 = "#9b9c84",
    light4 = "#81836f",
    red_bright = "#e15f65",
    green_bright = "#859c25",
    yellow_bright = "#cba219",
    blue_bright = "#489bba",
    magenta_bright = "#8a86d1",
    cyan_bright = "#4ba67a",
    orange_bright = "#e48e3f",
    purple_bright = "#639be1",
    red = "#d54c55",
    green = "#768a20",
    yellow = "#b79217",
    blue = "#3f8ba7",
    magenta = "#7973ca",
    cyan = "#42946c",
    orange = "#d18035",
    purple = "#4182d2",
    dark_red = "#722529",
    light_red = "#fc9487",
    dark_green = "#62693e",
    light_green = "#d5d39b",
    dark_aqua = "#49503b",
    light_aqua = "#e8e5b5",
    gray = "#ffff00",
}

-- get a hex list of gruvbox colors based on current bg and constrast config
local function get_colors()
    local p = Nightshade.palette
    local config = Nightshade.config

    for color, hex in pairs(config.palette_overrides) do
        p[color] = hex
    end

    return {
        bg0 = p.dark0,
        bg1 = p.dark1,
        bg2 = p.dark2,
        bg3 = p.dark3,
        bg4 = p.dark4,
        fg0 = p.light0,
        fg1 = p.light1,
        fg2 = p.light2,
        fg3 = p.light3,
        fg4 = p.light4,
        red_bright = p.red_bright,
        green_bright = p.green_bright,
        yellow_bright = p.yellow_bright,
        blue_bright = p.blue_bright,
        magenta_bright = p.magenta_bright,
        cyan_bright = p.cyan_bright,
        orange_bright = p.orange_bright,
        red = p.red,
        green = p.green,
        yellow = p.yellow,
        blue = p.blue,
        magenta = p.magenta,
        cyan = p.cyan,
        dark_red = p.dark_red,
        dark_green = p.dark_green,
        dark_aqua = p.dark_aqua,
        gray = p.gray,
    }
end

local function get_groups()
    local colors = get_colors()
    local config = Nightshade.config

    if config.terminal_colors then
        local term_colors = {
            colors.bg0,
            colors.red,
            colors.green,
            colors.yellow,
            colors.blue,
            colors.magenta,
            colors.cyan,
            colors.fg4,
            colors.gray,
            colors.red_bright,
            colors.green_bright,
            colors.yellow_bright,
            colors.blue_bright,
            colors.magenta_bright,
            colors.cyan_bright,
            colors.fg1,
        }
        for index, value in ipairs(term_colors) do
            vim.g["terminal_color_" .. index - 1] = value
        end
    end

    local groups = {
        NightshadeFg0 = { fg = colors.fg0 },
        NightshadeFg1 = { fg = colors.fg1 },
        NightshadeFg2 = { fg = colors.fg2 },
        NightshadeFg3 = { fg = colors.fg3 },
        NightshadeFg4 = { fg = colors.fg4 },
        NightshadeGray = { fg = colors.gray },
        NightshadeBg0 = { fg = colors.bg0 },
        NightshadeBg1 = { fg = colors.bg1 },
        NightshadeBg2 = { fg = colors.bg2 },
        NightshadeBg3 = { fg = colors.bg3 },
        NightshadeBg4 = { fg = colors.bg4 },
        NightshadeRed = { fg = colors.red_bright },
        NightshadeRedBold = { fg = colors.red_bright, bold = config.bold },
        NightshadeGreen = { fg = colors.green_bright },
        NightshadeGreenBold = { fg = colors.green_bright, bold = config.bold },
        NightshadeYellow = { fg = colors.yellow_bright },
        NightshadeYellowBold = { fg = colors.yellow_bright, bold = config.bold },
        NightshadeBlue = { fg = colors.blue_bright },
        NightshadeBlueBold = { fg = colors.blue_bright, bold = config.bold },
        NightshadePurple = { fg = colors.magenta_bright },
        NightshadePurpleBold = { fg = colors.magenta_bright, bold = config.bold },
        NightshadeAqua = { fg = colors.cyan_bright },
        NightshadeAquaBold = { fg = colors.cyan_bright, bold = config.bold },
        NightshadeOrange = { fg = colors.orange_bright },
        NightshadeOrangeBold = { fg = colors.orange_bright, bold = config.bold },
        NightshadeRedSign = config.transparent_mode and { fg = colors.red_bright, reverse = config.invert_signs }
            or { fg = colors.red_bright, bg = colors.bg1, reverse = config.invert_signs },
        NightshadeGreenSign = config.transparent_mode and { fg = colors.green_bright, reverse = config.invert_signs }
            or { fg = colors.green_bright, bg = colors.bg1, reverse = config.invert_signs },
        NightshadeYellowSign = config.transparent_mode and { fg = colors.yellow_bright, reverse = config.invert_signs }
            or { fg = colors.yellow_bright, bg = colors.bg1, reverse = config.invert_signs },
        NightshadeBlueSign = config.transparent_mode and { fg = colors.blue_bright, reverse = config.invert_signs }
            or { fg = colors.blue_bright, bg = colors.bg1, reverse = config.invert_signs },
        NightshadePurpleSign = config.transparent_mode
                and { fg = colors.magenta_bright, reverse = config.invert_signs }
            or { fg = colors.magenta_bright, bg = colors.bg1, reverse = config.invert_signs },
        NightshadeAquaSign = config.transparent_mode and { fg = colors.cyan_bright, reverse = config.invert_signs }
            or { fg = colors.cyan_bright, bg = colors.bg1, reverse = config.invert_signs },
        NightshadeOrangeSign = config.transparent_mode and { fg = colors.orange_bright, reverse = config.invert_signs }
            or { fg = colors.orange_bright, bg = colors.bg1, reverse = config.invert_signs },
        NightshadeRedUnderline = { undercurl = config.undercurl, sp = colors.red_bright },
        NightshadeGreenUnderline = { undercurl = config.undercurl, sp = colors.green_bright },
        NightshadeYellowUnderline = { undercurl = config.undercurl, sp = colors.yellow_bright },
        NightshadeBlueUnderline = { undercurl = config.undercurl, sp = colors.blue_bright },
        NightshadePurpleUnderline = { undercurl = config.undercurl, sp = colors.magenta_bright },
        NightshadeAquaUnderline = { undercurl = config.undercurl, sp = colors.cyan_bright },
        NightshadeOrangeUnderline = { undercurl = config.undercurl, sp = colors.orange_bright },
        Normal = config.transparent_mode and { fg = colors.fg1, bg = nil } or { fg = colors.fg1, bg = colors.bg0 },
        NormalFloat = config.transparent_mode and { fg = colors.fg1, bg = nil } or { fg = colors.fg1, bg = colors.bg1 },
        NormalNC = config.dim_inactive and { fg = colors.fg0, bg = colors.bg1 } or { link = "Normal" },
        CursorLine = { bg = colors.bg1 },
        CursorColumn = { link = "CursorLine" },
        TabLineFill = { fg = colors.bg4, bg = colors.bg1, reverse = config.invert_tabline },
        TabLineSel = { fg = colors.green_bright, bg = colors.bg1, reverse = config.invert_tabline },
        TabLine = { link = "TabLineFill" },
        MatchParen = { bg = colors.bg3, bold = config.bold },
        ColorColumn = { bg = colors.bg1 },
        Conceal = { fg = colors.blue_bright },
        CursorLineNr = { fg = colors.yellow_bright, bg = colors.bg1 },
        NonText = { link = "NightshadeBg2" },
        SpecialKey = { link = "NightshadeFg4" },
        Visual = { bg = colors.bg3, reverse = config.invert_selection },
        VisualNOS = { link = "Visual" },
        Search = { fg = colors.yellow_bright, bg = colors.bg0, reverse = config.inverse },
        IncSearch = { fg = colors.orange_bright, bg = colors.bg0, reverse = config.inverse },
        CurSearch = { link = "IncSearch" },
        QuickFixLine = { link = "NightshadePurple" },
        Underlined = { fg = colors.blue_bright, underline = config.underline },
        StatusLine = { fg = colors.fg1, bg = colors.bg2 },
        StatusLineNC = { fg = colors.fg4, bg = colors.bg1 },
        WinBar = { fg = colors.fg4, bg = colors.bg0 },
        WinBarNC = { fg = colors.fg3, bg = colors.bg1 },
        WinSeparator = config.transparent_mode and { fg = colors.bg3, bg = nil }
            or { fg = colors.bg3, bg = colors.bg0 },
        WildMenu = { fg = colors.blue_bright, bg = colors.bg2, bold = config.bold },
        Directory = { link = "NightshadeGreenBold" },
        Title = { link = "NightshadeGreenBold" },
        ErrorMsg = { fg = colors.bg0, bg = colors.red_bright, bold = config.bold },
        MoreMsg = { link = "NightshadeYellowBold" },
        ModeMsg = { link = "NightshadeYellowBold" },
        Question = { link = "NightshadeOrangeBold" },
        WarningMsg = { link = "NightshadeRedBold" },
        LineNr = { fg = colors.bg4 },
        SignColumn = config.transparent_mode and { bg = nil } or { bg = colors.bg1 },
        Folded = { fg = colors.gray, bg = colors.bg1, italic = config.italic.folds },
        FoldColumn = config.transparent_mode and { fg = colors.gray, bg = nil }
            or { fg = colors.gray, bg = colors.bg1 },
        Cursor = { reverse = config.inverse },
        vCursor = { link = "Cursor" },
        iCursor = { link = "Cursor" },
        lCursor = { link = "Cursor" },
        Special = { link = "NightshadeOrange" },
        Comment = { fg = colors.gray, italic = config.italic.comments },
        Todo = { fg = colors.bg0, bg = colors.yellow_bright, bold = config.bold, italic = config.italic.comments },
        Done = { fg = colors.orange_bright, bold = config.bold, italic = config.italic.comments },
        Error = { fg = colors.red_bright, bold = config.bold, reverse = config.inverse },
        Statement = { link = "NightshadeRed" },
        Conditional = { link = "NightshadeRed" },
        Repeat = { link = "NightshadeRed" },
        Label = { link = "NightshadeRed" },
        Exception = { link = "NightshadeRed" },
        Operator = { fg = colors.orange_bright, italic = config.italic.operators },
        Keyword = { link = "NightshadeRed" },
        Identifier = { link = "NightshadeBlue" },
        Function = { link = "NightshadeGreenBold" },
        PreProc = { link = "NightshadeAqua" },
        Include = { link = "NightshadeAqua" },
        Define = { link = "NightshadeAqua" },
        Macro = { link = "NightshadeAqua" },
        PreCondit = { link = "NightshadeAqua" },
        Constant = { link = "NightshadePurple" },
        Character = { link = "NightshadePurple" },
        String = { fg = colors.green_bright, italic = config.italic.strings },
        Boolean = { link = "NightshadePurple" },
        Number = { link = "NightshadePurple" },
        Float = { link = "NightshadePurple" },
        Type = { link = "NightshadeYellow" },
        StorageClass = { link = "NightshadeOrange" },
        Structure = { link = "NightshadeAqua" },
        Typedef = { link = "NightshadeYellow" },
        Pmenu = { fg = colors.fg1, bg = colors.bg2 },
        PmenuSel = { fg = colors.bg2, bg = colors.blue_bright, bold = config.bold },
        PmenuSbar = { bg = colors.bg2 },
        PmenuThumb = { bg = colors.bg4 },
        DiffDelete = { bg = colors.dark_red },
        DiffAdd = { bg = colors.dark_green },
        DiffChange = { bg = colors.dark_aqua },
        DiffText = { bg = colors.yellow_bright, fg = colors.bg0 },
        SpellCap = { link = "NightshadeBlueUnderline" },
        SpellBad = { link = "NightshadeRedUnderline" },
        SpellLocal = { link = "NightshadeAquaUnderline" },
        SpellRare = { link = "NightshadePurpleUnderline" },
        Whitespace = { fg = colors.bg2 },
        Delimiter = { link = "NightshadeOrange" },
        EndOfBuffer = { link = "NonText" },
        DiagnosticError = { link = "NightshadeRed" },
        DiagnosticWarn = { link = "NightshadeYellow" },
        DiagnosticInfo = { link = "NightshadeBlue" },
        DiagnosticDeprecated = { strikethrough = config.strikethrough },
        DiagnosticHint = { link = "NightshadeAqua" },
        DiagnosticOk = { link = "NightshadeGreen" },
        DiagnosticSignError = { link = "NightshadeRedSign" },
        DiagnosticSignWarn = { link = "NightshadeYellowSign" },
        DiagnosticSignInfo = { link = "NightshadeBlueSign" },
        DiagnosticSignHint = { link = "NightshadeAquaSign" },
        DiagnosticSignOk = { link = "NightshadeGreenSign" },
        DiagnosticUnderlineError = { link = "NightshadeRedUnderline" },
        DiagnosticUnderlineWarn = { link = "NightshadeYellowUnderline" },
        DiagnosticUnderlineInfo = { link = "NightshadeBlueUnderline" },
        DiagnosticUnderlineHint = { link = "NightshadeAquaUnderline" },
        DiagnosticUnderlineOk = { link = "NightshadeGreenUnderline" },
        DiagnosticFloatingError = { link = "NightshadeRed" },
        DiagnosticFloatingWarn = { link = "NightshadeOrange" },
        DiagnosticFloatingInfo = { link = "NightshadeBlue" },
        DiagnosticFloatingHint = { link = "NightshadeAqua" },
        DiagnosticFloatingOk = { link = "NightshadeGreen" },
        DiagnosticVirtualTextError = { link = "NightshadeRed" },
        DiagnosticVirtualTextWarn = { link = "NightshadeYellow" },
        DiagnosticVirtualTextInfo = { link = "NightshadeBlue" },
        DiagnosticVirtualTextHint = { link = "NightshadeAqua" },
        DiagnosticVirtualTextOk = { link = "NightshadeGreen" },
        LspReferenceRead = { link = "NightshadeYellowBold" },
        LspReferenceTarget = { link = "Visual" },
        LspReferenceText = { link = "NightshadeYellowBold" },
        LspReferenceWrite = { link = "NightshadeOrangeBold" },
        LspCodeLens = { link = "NightshadeGray" },
        LspSignatureActiveParameter = { link = "Search" },
        gitcommitSelectedFile = { link = "NightshadeGreen" },
        gitcommitDiscardedFile = { link = "NightshadeRed" },
        GitSignsAdd = { link = "NightshadeGreen" },
        GitSignsChange = { link = "NightshadeOrange" },
        GitSignsDelete = { link = "NightshadeRed" },
        NvimTreeSymlink = { fg = colors.cyan },
        NvimTreeRootFolder = { fg = colors.magenta, bold = true },
        NvimTreeFolderIcon = { fg = colors.blue, bold = true },
        NvimTreeFileIcon = { fg = colors.light2 },
        NvimTreeExecFile = { fg = colors.green, bold = true },
        NvimTreeOpenedFile = { fg = colors.bright_red, bold = true },
        NvimTreeSpecialFile = { fg = colors.yellow, bold = true, underline = true },
        NvimTreeImageFile = { fg = colors.magenta },
        NvimTreeIndentMarker = { fg = colors.dark3 },
        NvimTreeGitDirty = { fg = colors.yellow },
        NvimTreeGitStaged = { fg = colors.yellow },
        NvimTreeGitMerge = { fg = colors.magenta },
        NvimTreeGitRenamed = { fg = colors.magenta },
        NvimTreeGitNew = { fg = colors.yellow },
        NvimTreeGitDeleted = { fg = colors.red },
        NvimTreeWindowPicker = { bg = colors.cyan_bright },
        debugPC = { link = "DiffAdd" },
        debugBreakpoint = { link = "NightshadeRedSign" },
        StartifyBracket = { link = "NightshadeFg3" },
        StartifyFile = { link = "NightshadeFg1" },
        StartifyNumber = { link = "NightshadeBlue" },
        StartifyPath = { link = "NightshadeGray" },
        StartifySlash = { link = "NightshadeGray" },
        StartifySection = { link = "NightshadeYellow" },
        StartifySpecial = { link = "NightshadeBg2" },
        StartifyHeader = { link = "NightshadeOrange" },
        StartifyFooter = { link = "NightshadeBg2" },
        StartifyVar = { link = "StartifyPath" },
        StartifySelect = { link = "Title" },
        DirvishPathTail = { link = "NightshadeAqua" },
        DirvishArg = { link = "NightshadeYellow" },
        netrwDir = { link = "NightshadeAqua" },
        netrwClassify = { link = "NightshadeAqua" },
        netrwLink = { link = "NightshadeGray" },
        netrwSymLink = { link = "NightshadeFg1" },
        netrwExe = { link = "NightshadeYellow" },
        netrwComment = { link = "NightshadeGray" },
        netrwList = { link = "NightshadeBlue" },
        netrwHelpCmd = { link = "NightshadeAqua" },
        netrwCmdSep = { link = "NightshadeFg3" },
        netrwVersion = { link = "NightshadeGreen" },
        NERDTreeDir = { link = "NightshadeAqua" },
        NERDTreeDirSlash = { link = "NightshadeAqua" },
        NERDTreeOpenable = { link = "NightshadeOrange" },
        NERDTreeClosable = { link = "NightshadeOrange" },
        NERDTreeFile = { link = "NightshadeFg1" },
        NERDTreeExecFile = { link = "NightshadeYellow" },
        NERDTreeUp = { link = "NightshadeGray" },
        NERDTreeCWD = { link = "NightshadeGreen" },
        NERDTreeHelp = { link = "NightshadeFg1" },
        NERDTreeToggleOn = { link = "NightshadeGreen" },
        NERDTreeToggleOff = { link = "NightshadeRed" },
        CocErrorSign = { link = "NightshadeRedSign" },
        CocWarningSign = { link = "NightshadeOrangeSign" },
        CocInfoSign = { link = "NightshadeBlueSign" },
        CocHintSign = { link = "NightshadeAquaSign" },
        CocErrorFloat = { link = "NightshadeRed" },
        CocWarningFloat = { link = "NightshadeOrange" },
        CocInfoFloat = { link = "NightshadeBlue" },
        CocHintFloat = { link = "NightshadeAqua" },
        CocDiagnosticsError = { link = "NightshadeRed" },
        CocDiagnosticsWarning = { link = "NightshadeOrange" },
        CocDiagnosticsInfo = { link = "NightshadeBlue" },
        CocDiagnosticsHint = { link = "NightshadeAqua" },
        CocSearch = { link = "NightshadeBlue" },
        CocSelectedText = { link = "NightshadeRed" },
        CocMenuSel = { link = "PmenuSel" },
        CocCodeLens = { link = "NightshadeGray" },
        CocErrorHighlight = { link = "NightshadeRedUnderline" },
        CocWarningHighlight = { link = "NightshadeOrangeUnderline" },
        CocInfoHighlight = { link = "NightshadeBlueUnderline" },
        CocHintHighlight = { link = "NightshadeAquaUnderline" },
        SnacksPicker = { link = "NightshadeFg1" },
        SnacksPickerBorder = { link = "SnacksPicker" },
        SnacksPickerListCursorLine = { link = "CursorLine" },
        SnacksPickerMatch = { link = "NightshadeOrange" },
        SnacksPickerPrompt = { link = "NightshadeRed" },
        SnacksPickerTitle = { link = "SnacksPicker" },
        SnacksPickerDir = { link = "NightshadeGray" },
        SnacksPickerPathHidden = { link = "NightshadeGray" },
        SnacksPickerGitStatusUntracked = { link = "NightshadeGray" },
        SnacksPickerPathIgnored = { link = "NightshadeBg3" },
        TelescopeNormal = { link = "NightshadeFg1" },
        TelescopeSelection = { link = "CursorLine" },
        TelescopeSelectionCaret = { link = "NightshadeRed" },
        TelescopeMultiSelection = { link = "NightshadeGray" },
        TelescopeBorder = { link = "TelescopeNormal" },
        TelescopePromptBorder = { link = "TelescopeNormal" },
        TelescopeResultsBorder = { link = "TelescopeNormal" },
        TelescopePreviewBorder = { link = "TelescopeNormal" },
        TelescopeMatching = { link = "NightshadeOrange" },
        TelescopePromptPrefix = { link = "NightshadeRed" },
        TelescopePrompt = { link = "TelescopeNormal" },
        CmpItemAbbr = { link = "NightshadeFg0" },
        CmpItemAbbrDeprecated = { link = "NightshadeFg1" },
        CmpItemAbbrMatch = { link = "NightshadeBlueBold" },
        CmpItemAbbrMatchFuzzy = { link = "NightshadeBlueUnderline" },
        CmpItemMenu = { link = "NightshadeGray" },
        CmpItemKindText = { link = "NightshadeOrange" },
        CmpItemKindVariable = { link = "NightshadeOrange" },
        CmpItemKindMethod = { link = "NightshadeBlue" },
        CmpItemKindFunction = { link = "NightshadeBlue" },
        CmpItemKindConstructor = { link = "NightshadeYellow" },
        CmpItemKindUnit = { link = "NightshadeBlue" },
        CmpItemKindField = { link = "NightshadeBlue" },
        CmpItemKindClass = { link = "NightshadeYellow" },
        CmpItemKindInterface = { link = "NightshadeYellow" },
        CmpItemKindModule = { link = "NightshadeBlue" },
        CmpItemKindProperty = { link = "NightshadeBlue" },
        CmpItemKindValue = { link = "NightshadeOrange" },
        CmpItemKindEnum = { link = "NightshadeYellow" },
        CmpItemKindOperator = { link = "NightshadeYellow" },
        CmpItemKindKeyword = { link = "NightshadePurple" },
        CmpItemKindEvent = { link = "NightshadePurple" },
        CmpItemKindReference = { link = "NightshadePurple" },
        CmpItemKindColor = { link = "NightshadePurple" },
        CmpItemKindSnippet = { link = "NightshadeGreen" },
        CmpItemKindFile = { link = "NightshadeBlue" },
        CmpItemKindFolder = { link = "NightshadeBlue" },
        CmpItemKindEnumMember = { link = "NightshadeAqua" },
        CmpItemKindConstant = { link = "NightshadeOrange" },
        CmpItemKindStruct = { link = "NightshadeYellow" },
        CmpItemKindTypeParameter = { link = "NightshadeYellow" },
        CmpItemKindTextIcon = { link = "CmpItemKindText" },
        CmpItemKindVariableIcon = { link = "CmpItemKindVariable" },
        CmpItemKindMethodIcon = { link = "CmpItemKindMethod" },
        CmpItemKindFunctionIcon = { link = "CmpItemKindFunction" },
        CmpItemKindConstructorIcon = { link = "CmpItemKindConstructor" },
        CmpItemKindUnitIcon = { link = "CmpItemKindUnit" },
        CmpItemKindFieldIcon = { link = "CmpItemKindField" },
        CmpItemKindClassIcon = { link = "CmpItemKindClass" },
        CmpItemKindInterfaceIcon = { link = "CmpItemKindInterface" },
        CmpItemKindModuleIcon = { link = "CmpItemKindModule" },
        CmpItemKindPropertyIcon = { link = "CmpItemKindProperty" },
        CmpItemKindValueIcon = { link = "CmpItemKindValue" },
        CmpItemKindEnumIcon = { link = "CmpItemKindEnum" },
        CmpItemKindOperatorIcon = { link = "CmpItemKindOperator" },
        CmpItemKindKeywordIcon = { link = "CmpItemKindKeyword" },
        CmpItemKindEventIcon = { link = "CmpItemKindEvent" },
        CmpItemKindReferenceIcon = { link = "CmpItemKindReference" },
        CmpItemKindColorIcon = { link = "CmpItemKindColor" },
        CmpItemKindSnippetIcon = { link = "CmpItemKindSnippet" },
        CmpItemKindFileIcon = { link = "CmpItemKindFile" },
        CmpItemKindFolderIcon = { link = "CmpItemKindFolder" },
        CmpItemKindEnumMemberIcon = { link = "CmpItemKindEnumMember" },
        CmpItemKindConstantIcon = { link = "CmpItemKindConstant" },
        CmpItemKindStructIcon = { link = "CmpItemKindStruct" },
        CmpItemKindTypeParameterIcon = { link = "CmpItemKindTypeParameter" },
        BlinkPairsRed = { link = "NightshadeRed" },
        BlinkPairsOrange = { link = "NightshadeOrange" },
        BlinkPairsYellow = { link = "NightshadeYellow" },
        BlinkPairsGreen = { link = "NightshadeGreen" },
        BlinkPairsBlue = { link = "NightshadeBlue" },
        BlinkPairsCyan = { link = "NightshadeAqua" },
        BlinkPairsPurple = { link = "NightshadePurple" },
        BlinkIndentRed = { link = "NightshadeRed" },
        BlinkIndentOrange = { link = "NightshadeOrange" },
        BlinkIndentYellow = { link = "NightshadeYellow" },
        BlinkIndentGreen = { link = "NightshadeGreen" },
        BlinkIndentBlue = { link = "NightshadeBlue" },
        BlinkIndentCyan = { link = "NightshadeAqua" },
        BlinkIndentViolet = { link = "NightshadePurple" },
        BlinkIndentRedUnderline = { underline = true, sp = colors.red_bright },
        BlinkIndentOrangeUnderline = { underline = true, sp = colors.orange_bright },
        BlinkIndentYellowUnderline = { underline = true, sp = colors.yellow_bright },
        BlinkIndentGreenUnderline = { underline = true, sp = colors.green_bright },
        BlinkIndentBlueUnderline = { underline = true, sp = colors.blue_bright },
        BlinkIndentCyanUnderline = { underline = true, sp = colors.cyan_bright },
        BlinkIndentVioletUnderline = { underline = true, sp = colors.magenta_bright },
        BlinkCmpLabel = { link = "NightshadeFg0" },
        BlinkCmpLabelDeprecated = { link = "NightshadeFg1" },
        BlinkCmpLabelMatch = { link = "NightshadeBlueBold" },
        BlinkCmpLabelDetail = { link = "NightshadeGray" },
        BlinkCmpLabelDescription = { link = "NightshadeGray" },
        BlinkCmpKindText = { link = "NightshadeOrange" },
        BlinkCmpKindVariable = { link = "NightshadeOrange" },
        BlinkCmpKindMethod = { link = "NightshadeBlue" },
        BlinkCmpKindFunction = { link = "NightshadeBlue" },
        BlinkCmpKindConstructor = { link = "NightshadeYellow" },
        BlinkCmpKindUnit = { link = "NightshadeBlue" },
        BlinkCmpKindField = { link = "NightshadeBlue" },
        BlinkCmpKindClass = { link = "NightshadeYellow" },
        BlinkCmpKindInterface = { link = "NightshadeYellow" },
        BlinkCmpKindModule = { link = "NightshadeBlue" },
        BlinkCmpKindProperty = { link = "NightshadeBlue" },
        BlinkCmpKindValue = { link = "NightshadeOrange" },
        BlinkCmpKindEnum = { link = "NightshadeYellow" },
        BlinkCmpKindOperator = { link = "NightshadeYellow" },
        BlinkCmpKindKeyword = { link = "NightshadePurple" },
        BlinkCmpKindEvent = { link = "NightshadePurple" },
        BlinkCmpKindReference = { link = "NightshadePurple" },
        BlinkCmpKindColor = { link = "NightshadePurple" },
        BlinkCmpKindSnippet = { link = "NightshadeGreen" },
        BlinkCmpKindFile = { link = "NightshadeBlue" },
        BlinkCmpKindFolder = { link = "NightshadeBlue" },
        BlinkCmpKindEnumMember = { link = "NightshadeAqua" },
        BlinkCmpKindConstant = { link = "NightshadeOrange" },
        BlinkCmpKindStruct = { link = "NightshadeYellow" },
        BlinkCmpKindTypeParameter = { link = "NightshadeYellow" },
        BlinkCmpSource = { link = "NightshadeGray" },
        BlinkCmpGhostText = { link = "NightshadeBg4" },
        diffAdded = { link = "DiffAdd" },
        diffRemoved = { link = "DiffDelete" },
        diffChanged = { link = "DiffChange" },
        diffFile = { link = "NightshadeOrange" },
        diffNewFile = { link = "NightshadeYellow" },
        diffOldFile = { link = "NightshadeOrange" },
        diffLine = { link = "NightshadeBlue" },
        diffIndexLine = { link = "diffChanged" },
        NavicIconsFile = { link = "NightshadeBlue" },
        NavicIconsModule = { link = "NightshadeOrange" },
        NavicIconsNamespace = { link = "NightshadeBlue" },
        NavicIconsPackage = { link = "NightshadeAqua" },
        NavicIconsClass = { link = "NightshadeYellow" },
        NavicIconsMethod = { link = "NightshadeBlue" },
        NavicIconsProperty = { link = "NightshadeAqua" },
        NavicIconsField = { link = "NightshadePurple" },
        NavicIconsConstructor = { link = "NightshadeBlue" },
        NavicIconsEnum = { link = "NightshadePurple" },
        NavicIconsInterface = { link = "NightshadeGreen" },
        NavicIconsFunction = { link = "NightshadeBlue" },
        NavicIconsVariable = { link = "NightshadePurple" },
        NavicIconsConstant = { link = "NightshadeOrange" },
        NavicIconsString = { link = "NightshadeGreen" },
        NavicIconsNumber = { link = "NightshadeOrange" },
        NavicIconsBoolean = { link = "NightshadeOrange" },
        NavicIconsArray = { link = "NightshadeOrange" },
        NavicIconsObject = { link = "NightshadeOrange" },
        NavicIconsKey = { link = "NightshadeAqua" },
        NavicIconsNull = { link = "NightshadeOrange" },
        NavicIconsEnumMember = { link = "NightshadeYellow" },
        NavicIconsStruct = { link = "NightshadePurple" },
        NavicIconsEvent = { link = "NightshadeYellow" },
        NavicIconsOperator = { link = "NightshadeRed" },
        NavicIconsTypeParameter = { link = "NightshadeRed" },
        NavicText = { link = "NightshadeWhite" },
        NavicSeparator = { link = "NightshadeWhite" },
        htmlTag = { link = "NightshadeAquaBold" },
        htmlEndTag = { link = "NightshadeAquaBold" },
        htmlTagName = { link = "NightshadeBlue" },
        htmlArg = { link = "NightshadeOrange" },
        htmlTagN = { link = "NightshadeFg1" },
        htmlSpecialTagName = { link = "NightshadeBlue" },
        htmlLink = { fg = colors.fg4, underline = config.underline },
        htmlSpecialChar = { link = "NightshadeRed" },
        htmlBold = { fg = colors.fg0, bg = colors.bg0, bold = config.bold },
        htmlBoldUnderline = { fg = colors.fg0, bg = colors.bg0, bold = config.bold, underline = config.underline },
        htmlBoldItalic = { fg = colors.fg0, bg = colors.bg0, bold = config.bold, italic = true },
        htmlBoldUnderlineItalic = {
            fg = colors.fg0,
            bg = colors.bg0,
            bold = config.bold,
            italic = true,
            underline = config.underline,
        },
        htmlUnderline = { fg = colors.fg0, bg = colors.bg0, underline = config.underline },
        htmlUnderlineItalic = {
            fg = colors.fg0,
            bg = colors.bg0,
            italic = true,
            underline = config.underline,
        },
        htmlItalic = { fg = colors.fg0, bg = colors.bg0, italic = true },
        xmlTag = { link = "NightshadeAquaBold" },
        xmlEndTag = { link = "NightshadeAquaBold" },
        xmlTagName = { link = "NightshadeBlue" },
        xmlEqual = { link = "NightshadeBlue" },
        docbkKeyword = { link = "NightshadeAquaBold" },
        xmlDocTypeDecl = { link = "NightshadeGray" },
        xmlDocTypeKeyword = { link = "NightshadePurple" },
        xmlCdataStart = { link = "NightshadeGray" },
        xmlCdataCdata = { link = "NightshadePurple" },
        dtdFunction = { link = "NightshadeGray" },
        dtdTagName = { link = "NightshadePurple" },
        xmlAttrib = { link = "NightshadeOrange" },
        xmlProcessingDelim = { link = "NightshadeGray" },
        dtdParamEntityPunct = { link = "NightshadeGray" },
        dtdParamEntityDPunct = { link = "NightshadeGray" },
        xmlAttribPunct = { link = "NightshadeGray" },
        xmlEntity = { link = "NightshadeRed" },
        xmlEntityPunct = { link = "NightshadeRed" },
        clojureKeyword = { link = "NightshadeBlue" },
        clojureCond = { link = "NightshadeOrange" },
        clojureSpecial = { link = "NightshadeOrange" },
        clojureDefine = { link = "NightshadeOrange" },
        clojureFunc = { link = "NightshadeYellow" },
        clojureRepeat = { link = "NightshadeYellow" },
        clojureCharacter = { link = "NightshadeAqua" },
        clojureStringEscape = { link = "NightshadeAqua" },
        clojureException = { link = "NightshadeRed" },
        clojureRegexp = { link = "NightshadeAqua" },
        clojureRegexpEscape = { link = "NightshadeAqua" },
        clojureRegexpCharClass = { fg = colors.fg3, bold = config.bold },
        clojureRegexpMod = { link = "clojureRegexpCharClass" },
        clojureRegexpQuantifier = { link = "clojureRegexpCharClass" },
        clojureParen = { link = "NightshadeFg3" },
        clojureAnonArg = { link = "NightshadeYellow" },
        clojureVariable = { link = "NightshadeBlue" },
        clojureMacro = { link = "NightshadeOrange" },
        clojureMeta = { link = "NightshadeYellow" },
        clojureDeref = { link = "NightshadeYellow" },
        clojureQuote = { link = "NightshadeYellow" },
        clojureUnquote = { link = "NightshadeYellow" },
        cOperator = { link = "NightshadePurple" },
        cppOperator = { link = "NightshadePurple" },
        cStructure = { link = "NightshadeOrange" },
        pythonBuiltin = { link = "NightshadeOrange" },
        pythonBuiltinObj = { link = "NightshadeOrange" },
        pythonBuiltinFunc = { link = "NightshadeOrange" },
        pythonFunction = { link = "NightshadeAqua" },
        pythonDecorator = { link = "NightshadeRed" },
        pythonInclude = { link = "NightshadeBlue" },
        pythonImport = { link = "NightshadeBlue" },
        pythonRun = { link = "NightshadeBlue" },
        pythonCoding = { link = "NightshadeBlue" },
        pythonOperator = { link = "NightshadeRed" },
        pythonException = { link = "NightshadeRed" },
        pythonExceptions = { link = "NightshadePurple" },
        pythonBoolean = { link = "NightshadePurple" },
        pythonDot = { link = "NightshadeFg3" },
        pythonConditional = { link = "NightshadeRed" },
        pythonRepeat = { link = "NightshadeRed" },
        pythonDottedName = { link = "NightshadeGreenBold" },
        cssBraces = { link = "NightshadeBlue" },
        cssFunctionName = { link = "NightshadeYellow" },
        cssIdentifier = { link = "NightshadeOrange" },
        cssClassName = { link = "NightshadeGreen" },
        cssColor = { link = "NightshadeBlue" },
        cssSelectorOp = { link = "NightshadeBlue" },
        cssSelectorOp2 = { link = "NightshadeBlue" },
        cssImportant = { link = "NightshadeGreen" },
        cssVendor = { link = "NightshadeFg1" },
        cssTextProp = { link = "NightshadeAqua" },
        cssAnimationProp = { link = "NightshadeAqua" },
        cssUIProp = { link = "NightshadeYellow" },
        cssTransformProp = { link = "NightshadeAqua" },
        cssTransitionProp = { link = "NightshadeAqua" },
        cssPrintProp = { link = "NightshadeAqua" },
        cssPositioningProp = { link = "NightshadeYellow" },
        cssBoxProp = { link = "NightshadeAqua" },
        cssFontDescriptorProp = { link = "NightshadeAqua" },
        cssFlexibleBoxProp = { link = "NightshadeAqua" },
        cssBorderOutlineProp = { link = "NightshadeAqua" },
        cssBackgroundProp = { link = "NightshadeAqua" },
        cssMarginProp = { link = "NightshadeAqua" },
        cssListProp = { link = "NightshadeAqua" },
        cssTableProp = { link = "NightshadeAqua" },
        cssFontProp = { link = "NightshadeAqua" },
        cssPaddingProp = { link = "NightshadeAqua" },
        cssDimensionProp = { link = "NightshadeAqua" },
        cssRenderProp = { link = "NightshadeAqua" },
        cssColorProp = { link = "NightshadeAqua" },
        cssGeneratedContentProp = { link = "NightshadeAqua" },
        javaScriptBraces = { link = "NightshadeFg1" },
        javaScriptFunction = { link = "NightshadeAqua" },
        javaScriptIdentifier = { link = "NightshadeRed" },
        javaScriptMember = { link = "NightshadeBlue" },
        javaScriptNumber = { link = "NightshadePurple" },
        javaScriptNull = { link = "NightshadePurple" },
        javaScriptParens = { link = "NightshadeFg3" },
        typescriptReserved = { link = "NightshadeAqua" },
        typescriptLabel = { link = "NightshadeAqua" },
        typescriptFuncKeyword = { link = "NightshadeAqua" },
        typescriptIdentifier = { link = "NightshadeOrange" },
        typescriptBraces = { link = "NightshadeFg1" },
        typescriptEndColons = { link = "NightshadeFg1" },
        typescriptDOMObjects = { link = "NightshadeFg1" },
        typescriptAjaxMethods = { link = "NightshadeFg1" },
        typescriptLogicSymbols = { link = "NightshadeFg1" },
        typescriptDocSeeTag = { link = "Comment" },
        typescriptDocParam = { link = "Comment" },
        typescriptDocTags = { link = "vimCommentTitle" },
        typescriptGlobalObjects = { link = "NightshadeFg1" },
        typescriptParens = { link = "NightshadeFg3" },
        typescriptOpSymbols = { link = "NightshadeFg3" },
        typescriptHtmlElemProperties = { link = "NightshadeFg1" },
        typescriptNull = { link = "NightshadePurple" },
        typescriptInterpolationDelimiter = { link = "NightshadeAqua" },
        purescriptModuleKeyword = { link = "NightshadeAqua" },
        purescriptModuleName = { link = "NightshadeFg1" },
        purescriptWhere = { link = "NightshadeAqua" },
        purescriptDelimiter = { link = "NightshadeFg4" },
        purescriptType = { link = "NightshadeFg1" },
        purescriptImportKeyword = { link = "NightshadeAqua" },
        purescriptHidingKeyword = { link = "NightshadeAqua" },
        purescriptAsKeyword = { link = "NightshadeAqua" },
        purescriptStructure = { link = "NightshadeAqua" },
        purescriptOperator = { link = "NightshadeBlue" },
        purescriptTypeVar = { link = "NightshadeFg1" },
        purescriptConstructor = { link = "NightshadeFg1" },
        purescriptFunction = { link = "NightshadeFg1" },
        purescriptConditional = { link = "NightshadeOrange" },
        purescriptBacktick = { link = "NightshadeOrange" },
        coffeeExtendedOp = { link = "NightshadeFg3" },
        coffeeSpecialOp = { link = "NightshadeFg3" },
        coffeeCurly = { link = "NightshadeOrange" },
        coffeeParen = { link = "NightshadeFg3" },
        coffeeBracket = { link = "NightshadeOrange" },
        rubyStringDelimiter = { link = "NightshadeGreen" },
        rubyInterpolationDelimiter = { link = "NightshadeAqua" },
        rubyDefinedOperator = { link = "rubyKeyword" },
        objcTypeModifier = { link = "NightshadeRed" },
        objcDirective = { link = "NightshadeBlue" },
        goDirective = { link = "NightshadeAqua" },
        goConstants = { link = "NightshadePurple" },
        goDeclaration = { link = "NightshadeRed" },
        goDeclType = { link = "NightshadeBlue" },
        goBuiltins = { link = "NightshadeOrange" },
        luaIn = { link = "NightshadeRed" },
        luaFunction = { link = "NightshadeAqua" },
        luaTable = { link = "NightshadeOrange" },
        moonSpecialOp = { link = "NightshadeFg3" },
        moonExtendedOp = { link = "NightshadeFg3" },
        moonFunction = { link = "NightshadeFg3" },
        moonObject = { link = "NightshadeYellow" },
        javaAnnotation = { link = "NightshadeBlue" },
        javaDocTags = { link = "NightshadeAqua" },
        javaCommentTitle = { link = "vimCommentTitle" },
        javaParen = { link = "NightshadeFg3" },
        javaParen1 = { link = "NightshadeFg3" },
        javaParen2 = { link = "NightshadeFg3" },
        javaParen3 = { link = "NightshadeFg3" },
        javaParen4 = { link = "NightshadeFg3" },
        javaParen5 = { link = "NightshadeFg3" },
        javaOperator = { link = "NightshadeOrange" },
        javaVarArg = { link = "NightshadeGreen" },
        elixirDocString = { link = "Comment" },
        elixirStringDelimiter = { link = "NightshadeGreen" },
        elixirInterpolationDelimiter = { link = "NightshadeAqua" },
        elixirModuleDeclaration = { link = "NightshadeYellow" },
        scalaNameDefinition = { link = "NightshadeFg1" },
        scalaCaseFollowing = { link = "NightshadeFg1" },
        scalaCapitalWord = { link = "NightshadeFg1" },
        scalaTypeExtension = { link = "NightshadeFg1" },
        scalaKeyword = { link = "NightshadeRed" },
        scalaKeywordModifier = { link = "NightshadeRed" },
        scalaSpecial = { link = "NightshadeAqua" },
        scalaOperator = { link = "NightshadeFg1" },
        scalaTypeDeclaration = { link = "NightshadeYellow" },
        scalaTypeTypePostDeclaration = { link = "NightshadeYellow" },
        scalaInstanceDeclaration = { link = "NightshadeFg1" },
        scalaInterpolation = { link = "NightshadeAqua" },
        markdownItalic = { fg = colors.fg3, italic = true },
        markdownBold = { fg = colors.fg3, bold = config.bold },
        markdownBoldItalic = { fg = colors.fg3, bold = config.bold, italic = true },
        markdownH1 = { link = "NightshadeGreenBold" },
        markdownH2 = { link = "NightshadeGreenBold" },
        markdownH3 = { link = "NightshadeYellowBold" },
        markdownH4 = { link = "NightshadeYellowBold" },
        markdownH5 = { link = "NightshadeYellow" },
        markdownH6 = { link = "NightshadeYellow" },
        markdownCode = { link = "NightshadeAqua" },
        markdownCodeBlock = { link = "NightshadeAqua" },
        markdownCodeDelimiter = { link = "NightshadeAqua" },
        markdownBlockquote = { link = "NightshadeGray" },
        markdownListMarker = { link = "NightshadeGray" },
        markdownOrderedListMarker = { link = "NightshadeGray" },
        markdownRule = { link = "NightshadeGray" },
        markdownHeadingRule = { link = "NightshadeGray" },
        markdownUrlDelimiter = { link = "NightshadeFg3" },
        markdownLinkDelimiter = { link = "NightshadeFg3" },
        markdownLinkTextDelimiter = { link = "NightshadeFg3" },
        markdownHeadingDelimiter = { link = "NightshadeOrange" },
        markdownUrl = { link = "NightshadePurple" },
        markdownUrlTitleDelimiter = { link = "NightshadeGreen" },
        markdownLinkText = { fg = colors.gray, underline = config.underline },
        markdownIdDeclaration = { link = "markdownLinkText" },
        haskellType = { link = "NightshadeBlue" },
        haskellIdentifier = { link = "NightshadeAqua" },
        haskellSeparator = { link = "NightshadeFg4" },
        haskellDelimiter = { link = "NightshadeOrange" },
        haskellOperators = { link = "NightshadePurple" },
        haskellBacktick = { link = "NightshadeOrange" },
        haskellStatement = { link = "NightshadePurple" },
        haskellConditional = { link = "NightshadePurple" },
        haskellLet = { link = "NightshadeRed" },
        haskellDefault = { link = "NightshadeRed" },
        haskellWhere = { link = "NightshadeRed" },
        haskellBottom = { link = "NightshadeRedBold" },
        haskellImportKeywords = { link = "NightshadePurpleBold" },
        haskellDeclKeyword = { link = "NightshadeOrange" },
        haskellDecl = { link = "NightshadeOrange" },
        haskellDeriving = { link = "NightshadePurple" },
        haskellAssocType = { link = "NightshadeAqua" },
        haskellNumber = { link = "NightshadeAqua" },
        haskellPragma = { link = "NightshadeRedBold" },
        haskellTH = { link = "NightshadeAquaBold" },
        haskellForeignKeywords = { link = "NightshadeGreen" },
        haskellKeyword = { link = "NightshadeRed" },
        haskellFloat = { link = "NightshadeAqua" },
        haskellInfix = { link = "NightshadePurple" },
        haskellQuote = { link = "NightshadeGreenBold" },
        haskellShebang = { link = "NightshadeYellowBold" },
        haskellLiquid = { link = "NightshadePurpleBold" },
        haskellQuasiQuoted = { link = "NightshadeBlueBold" },
        haskellRecursiveDo = { link = "NightshadePurple" },
        haskellQuotedType = { link = "NightshadeRed" },
        haskellPreProc = { link = "NightshadeFg4" },
        haskellTypeRoles = { link = "NightshadeRedBold" },
        haskellTypeForall = { link = "NightshadeRed" },
        haskellPatternKeyword = { link = "NightshadeBlue" },
        jsonKeyword = { link = "NightshadeGreen" },
        jsonQuote = { link = "NightshadeGreen" },
        jsonBraces = { link = "NightshadeFg1" },
        jsonString = { link = "NightshadeFg1" },
        mailQuoted1 = { link = "NightshadeAqua" },
        mailQuoted2 = { link = "NightshadePurple" },
        mailQuoted3 = { link = "NightshadeYellow" },
        mailQuoted4 = { link = "NightshadeGreen" },
        mailQuoted5 = { link = "NightshadeRed" },
        mailQuoted6 = { link = "NightshadeOrange" },
        mailSignature = { link = "Comment" },
        csBraces = { link = "NightshadeFg1" },
        csEndColon = { link = "NightshadeFg1" },
        csLogicSymbols = { link = "NightshadeFg1" },
        csParens = { link = "NightshadeFg3" },
        csOpSymbols = { link = "NightshadeFg3" },
        csInterpolationDelimiter = { link = "NightshadeFg3" },
        csInterpolationAlignDel = { link = "NightshadeAquaBold" },
        csInterpolationFormat = { link = "NightshadeAqua" },
        csInterpolationFormatDel = { link = "NightshadeAquaBold" },
        rustSigil = { link = "NightshadeOrange" },
        rustEscape = { link = "NightshadeAqua" },
        rustStringContinuation = { link = "NightshadeAqua" },
        rustEnum = { link = "NightshadeAqua" },
        rustStructure = { link = "NightshadeAqua" },
        rustModPathSep = { link = "NightshadeFg2" },
        rustCommentLineDoc = { link = "Comment" },
        rustDefault = { link = "NightshadeAqua" },
        ocamlOperator = { link = "NightshadeFg1" },
        ocamlKeyChar = { link = "NightshadeOrange" },
        ocamlArrow = { link = "NightshadeOrange" },
        ocamlInfixOpKeyword = { link = "NightshadeRed" },
        ocamlConstructor = { link = "NightshadeOrange" },
        LspSagaCodeActionTitle = { link = "Title" },
        LspSagaCodeActionBorder = { link = "NightshadeFg1" },
        LspSagaCodeActionContent = { fg = colors.green_bright, bold = config.bold },
        LspSagaLspFinderBorder = { link = "NightshadeFg1" },
        LspSagaAutoPreview = { link = "NightshadeOrange" },
        TargetWord = { fg = colors.blue_bright, bold = config.bold },
        FinderSeparator = { link = "NightshadeAqua" },
        LspSagaDefPreviewBorder = { link = "NightshadeBlue" },
        LspSagaHoverBorder = { link = "NightshadeOrange" },
        LspSagaRenameBorder = { link = "NightshadeBlue" },
        LspSagaDiagnosticSource = { link = "NightshadeOrange" },
        LspSagaDiagnosticBorder = { link = "NightshadePurple" },
        LspSagaDiagnosticHeader = { link = "NightshadeGreen" },
        LspSagaSignatureHelpBorder = { link = "NightshadeGreen" },
        SagaShadow = { link = "NightshadeBg0" },
        DashboardShortCut = { link = "NightshadeOrange" },
        DashboardHeader = { link = "NightshadeAqua" },
        DashboardCenter = { link = "NightshadeYellow" },
        DashboardFooter = { fg = colors.magenta_bright, italic = true },
        MasonHighlight = { link = "NightshadeAqua" },
        MasonHighlightBlock = { fg = colors.bg0, bg = colors.blue_bright },
        MasonHighlightBlockBold = { fg = colors.bg0, bg = colors.blue_bright, bold = true },
        MasonHighlightSecondary = { fg = colors.yellow_bright },
        MasonHighlightBlockSecondary = { fg = colors.bg0, bg = colors.yellow_bright },
        MasonHighlightBlockBoldSecondary = { fg = colors.bg0, bg = colors.yellow_bright, bold = true },
        MasonHeader = { link = "MasonHighlightBlockBoldSecondary" },
        MasonHeaderSecondary = { link = "MasonHighlightBlockBold" },
        MasonMuted = { fg = colors.fg4 },
        MasonMutedBlock = { fg = colors.bg0, bg = colors.fg4 },
        MasonMutedBlockBold = { fg = colors.bg0, bg = colors.fg4, bold = true },
        LspInlayHint = { link = "comment" },
        CarbonFile = { link = "NightshadeFg1" },
        CarbonExe = { link = "NightshadeYellow" },
        CarbonSymlink = { link = "NightshadeAqua" },
        CarbonBrokenSymlink = { link = "NightshadeRed" },
        CarbonIndicator = { link = "NightshadeGray" },
        CarbonDanger = { link = "NightshadeRed" },
        CarbonPending = { link = "NightshadeYellow" },
        NoiceCursor = { link = "TermCursor" },
        NoiceCmdlinePopupBorder = { fg = colors.blue_bright, bg = nil },
        NoiceCmdlineIcon = { link = "NoiceCmdlinePopupBorder" },
        NoiceConfirmBorder = { link = "NoiceCmdlinePopupBorder" },
        NoiceCmdlinePopupBorderSearch = { fg = colors.yellow_bright, bg = nil },
        NoiceCmdlineIconSearch = { link = "NoiceCmdlinePopupBorderSearch" },
        NotifyDEBUGBorder = { link = "NightshadeBlue" },
        NotifyDEBUGIcon = { link = "NightshadeBlue" },
        NotifyDEBUGTitle = { link = "NightshadeBlue" },
        NotifyERRORBorder = { link = "NightshadeRed" },
        NotifyERRORIcon = { link = "NightshadeRed" },
        NotifyERRORTitle = { link = "NightshadeRed" },
        NotifyINFOBorder = { link = "NightshadeAqua" },
        NotifyINFOIcon = { link = "NightshadeAqua" },
        NotifyINFOTitle = { link = "NightshadeAqua" },
        NotifyTRACEBorder = { link = "NightshadeGreen" },
        NotifyTRACEIcon = { link = "NightshadeGreen" },
        NotifyTRACETitle = { link = "NightshadeGreen" },
        NotifyWARNBorder = { link = "NightshadeYellow" },
        NotifyWARNIcon = { link = "NightshadeYellow" },
        NotifyWARNTitle = { link = "NightshadeYellow" },
        IlluminatedWordText = { link = "LspReferenceText" },
        IlluminatedWordRead = { link = "LspReferenceRead" },
        IlluminatedWordWrite = { link = "LspReferenceWrite" },
        TSRainbowRed = { fg = colors.red_bright },
        TSRainbowOrange = { fg = colors.orange_bright },
        TSRainbowYellow = { fg = colors.yellow_bright },
        TSRainbowGreen = { fg = colors.green_bright },
        TSRainbowBlue = { fg = colors.blue_bright },
        TSRainbowViolet = { fg = colors.magenta_bright },
        TSRainbowCyan = { fg = colors.cyan_bright },
        RainbowDelimiterRed = { fg = colors.red_bright },
        RainbowDelimiterOrange = { fg = colors.orange_bright },
        RainbowDelimiterYellow = { fg = colors.yellow_bright },
        RainbowDelimiterGreen = { fg = colors.green_bright },
        RainbowDelimiterBlue = { fg = colors.blue_bright },
        RainbowDelimiterViolet = { fg = colors.magenta_bright },
        RainbowDelimiterCyan = { fg = colors.cyan_bright },
        DapBreakpointSymbol = { fg = colors.red_bright, bg = colors.bg1 },
        DapStoppedSymbol = { fg = colors.green_bright, bg = colors.bg1 },
        DapUIBreakpointsCurrentLine = { link = "NightshadeYellow" },
        DapUIBreakpointsDisabledLine = { link = "NightshadeGray" },
        DapUIBreakpointsInfo = { link = "NightshadeAqua" },
        DapUIBreakpointsLine = { link = "NightshadeYellow" },
        DapUIBreakpointsPath = { link = "NightshadeBlue" },
        DapUICurrentFrameName = { link = "NightshadePurple" },
        DapUIDecoration = { link = "NightshadePurple" },
        DapUIEndofBuffer = { link = "EndOfBuffer" },
        DapUIFloatBorder = { link = "NightshadeAqua" },
        DapUILineNumber = { link = "NightshadeYellow" },
        DapUIModifiedValue = { link = "NightshadeRed" },
        DapUIPlayPause = { fg = colors.green_bright, bg = colors.bg1 },
        DapUIRestart = { fg = colors.green_bright, bg = colors.bg1 },
        DapUIScope = { link = "NightshadeBlue" },
        DapUISource = { link = "NightshadeFg1" },
        DapUIStepBack = { fg = colors.blue_bright, bg = colors.bg1 },
        DapUIStepInto = { fg = colors.blue_bright, bg = colors.bg1 },
        DapUIStepOut = { fg = colors.blue_bright, bg = colors.bg1 },
        DapUIStepOver = { fg = colors.blue_bright, bg = colors.bg1 },
        DapUIStop = { fg = colors.red_bright, bg = colors.bg1 },
        DapUIStoppedThread = { link = "NightshadeBlue" },
        DapUIThread = { link = "NightshadeBlue" },
        DapUIType = { link = "NightshadeOrange" },
        DapUIUnavailable = { link = "NightshadeGray" },
        DapUIWatchesEmpty = { link = "NightshadeGray" },
        DapUIWatchesError = { link = "NightshadeRed" },
        DapUIWatchesValue = { link = "NightshadeYellow" },
        DapUIWinSelect = { link = "NightshadeYellow" },
        NeogitDiffDelete = { link = "DiffDelete" },
        NeogitDiffAdd = { link = "DiffAdd" },
        NeogitHunkHeader = { link = "WinBar" },
        NeogitHunkHeaderHighlight = { link = "WinBarNC" },
        DiffviewStatusModified = { link = "NightshadeGreenBold" },
        DiffviewFilePanelInsertions = { link = "NightshadeGreenBold" },
        DiffviewFilePanelDeletions = { link = "NightshadeRedBold" },
        MiniAnimateCursor = { reverse = true, nocombine = true },
        MiniAnimateNormalFloat = { fg = colors.fg1, bg = colors.bg1 },
        MiniClueBorder = { link = "FloatBorder" },
        MiniClueDescGroup = { link = "DiagnosticFloatingWarn" },
        MiniClueDescSingle = { link = "NormalFloat" },
        MiniClueNextKey = { link = "DiagnosticFloatingHint" },
        MiniClueNextKeyWithPostkeys = { link = "DiagnosticFloatingError" },
        MiniClueSeparator = { link = "DiagnosticFloatingInfo" },
        MiniClueTitle = { link = "FloatTitle" },
        MiniCompletionActiveParameter = { underline = true },
        MiniCursorword = { underline = true },
        MiniCursorwordCurrent = { underline = true },
        MiniDepsChangeAdded = { link = "NightshadeGreen" },
        MiniDepsChangeRemoved = { link = "NightshadeRed" },
        MiniDepsHint = { link = "DiagnosticHint" },
        MiniDepsInfo = { link = "DiagnosticInfo" },
        MiniDepsMsgBreaking = { link = "DiagnosticWarn" },
        MiniDepsPlaceholder = { link = "Comment" },
        MiniDepsTitle = { link = "Title" },
        MiniDepsTitleError = { link = "DiffDelete" },
        MiniDepsTitleSame = { link = "DiffChange" },
        MiniDepsTitleUpdate = { link = "DiffAdd" },
        MiniDiffOverAdd = { link = "DiffAdd" },
        MiniDiffOverChange = { link = "DiffText" },
        MiniDiffOverContext = { link = "DiffChange" },
        MiniDiffOverDelete = { link = "DiffDelete" },
        MiniDiffSignAdd = { link = "NightshadeGreen" },
        MiniDiffSignChange = { link = "NightshadeAqua" },
        MiniDiffSignDelete = { link = "NightshadeRed" },
        MiniFilesBorder = { link = "FloatBorder" },
        MiniFilesBorderModified = { link = "DiagnosticFloatingWarn" },
        MiniFilesCursorLine = { bg = colors.bg2 },
        MiniFilesDirectory = { link = "Directory" },
        MiniFilesFile = { link = "NightshadeFg1" },
        MiniFilesNormal = { link = "NormalFloat" },
        MiniFilesTitle = { link = "FloatTitle" },
        MiniFilesTitleFocused = { link = "NightshadeOrangeBold" },
        MiniHipatternsFixme = { fg = colors.bg0, bg = colors.red_bright, bold = config.bold },
        MiniHipatternsHack = { fg = colors.bg0, bg = colors.yellow_bright, bold = config.bold },
        MiniHipatternsNote = { fg = colors.bg0, bg = colors.blue_bright, bold = config.bold },
        MiniHipatternsTodo = { fg = colors.bg0, bg = colors.cyan_bright, bold = config.bold },
        MiniIconsAzure = { link = "NightshadeBlue" },
        MiniIconsBlue = { link = "NightshadeBlue" },
        MiniIconsCyan = { link = "NightshadeAqua" },
        MiniIconsGreen = { link = "NightshadeGreen" },
        MiniIconsGrey = { link = "NightshadeFg0" },
        MiniIconsOrange = { link = "NightshadeOrange" },
        MiniIconsPurple = { link = "NightshadePurple" },
        MiniIconsRed = { link = "NightshadeRed" },
        MiniIconsYellow = { link = "NightshadeYellow" },
        MiniIndentscopeSymbol = { link = "NightshadeGray" },
        MiniIndentscopeSymbolOff = { link = "NightshadeYellow" },
        MiniJump = { link = "NightshadeOrangeUnderline" },
        MiniJump2dDim = { link = "NightshadeGray" },
        MiniJump2dSpot = { fg = colors.orange_bright, bold = config.bold, nocombine = true },
        MiniJump2dSpotAhead = { fg = colors.cyan_bright, bg = colors.bg0, nocombine = true },
        MiniJump2dSpotUnique = { fg = colors.yellow_bright, bold = config.bold, nocombine = true },
        MiniMapNormal = { link = "NormalFloat" },
        MiniMapSymbolCount = { link = "Special" },
        MiniMapSymbolLine = { link = "Title" },
        MiniMapSymbolView = { link = "Delimiter" },
        MiniNotifyBorder = { link = "FloatBorder" },
        MiniNotifyNormal = { link = "NormalFloat" },
        MiniNotifyTitle = { link = "FloatTitle" },
        MiniOperatorsExchangeFrom = { link = "IncSearch" },
        MiniPickBorder = { link = "FloatBorder" },
        MiniPickBorderBusy = { link = "DiagnosticFloatingWarn" },
        MiniPickBorderText = { link = "FloatTitle" },
        MiniPickIconDirectory = { link = "Directory" },
        MiniPickIconFile = { link = "MiniPickNormal" },
        MiniPickHeader = { link = "DiagnosticFloatingHint" },
        MiniPickMatchCurrent = { bg = colors.bg2 },
        MiniPickMatchMarked = { link = "Visual" },
        MiniPickMatchRanges = { link = "DiagnosticFloatingHint" },
        MiniPickNormal = { link = "NormalFloat" },
        MiniPickPreviewLine = { link = "CursorLine" },
        MiniPickPreviewRegion = { link = "IncSearch" },
        MiniPickPrompt = { link = "DiagnosticFloatingInfo" },
        MiniStarterCurrent = { nocombine = true },
        MiniStarterFooter = { link = "NightshadeGray" },
        MiniStarterHeader = { link = "Title" },
        MiniStarterInactive = { link = "Comment" },
        MiniStarterItem = { link = "Normal" },
        MiniStarterItemBullet = { link = "Delimiter" },
        MiniStarterItemPrefix = { link = "WarningMsg" },
        MiniStarterSection = { link = "Delimiter" },
        MiniStarterQuery = { link = "MoreMsg" },
        MiniStatuslineDevinfo = { link = "StatusLine" },
        MiniStatuslineFileinfo = { link = "StatusLine" },
        MiniStatuslineFilename = { link = "StatusLineNC" },
        MiniStatuslineInactive = { link = "StatusLineNC" },
        MiniStatuslineModeCommand = { fg = colors.bg0, bg = colors.yellow_bright, bold = config.bold, nocombine = true },
        MiniStatuslineModeInsert = { fg = colors.bg0, bg = colors.blue_bright, bold = config.bold, nocombine = true },
        MiniStatuslineModeNormal = { fg = colors.bg0, bg = colors.fg1, bold = config.bold, nocombine = true },
        MiniStatuslineModeOther = { fg = colors.bg0, bg = colors.cyan_bright, bold = config.bold, nocombine = true },
        MiniStatuslineModeReplace = { fg = colors.bg0, bg = colors.red_bright, bold = config.bold, nocombine = true },
        MiniStatuslineModeVisual = { fg = colors.bg0, bg = colors.green_bright, bold = config.bold, nocombine = true },
        MiniSurround = { link = "IncSearch" },
        MiniTablineCurrent = {
            fg = colors.green_bright,
            bg = colors.bg1,
            bold = config.bold,
            reverse = config.invert_tabline,
        },
        MiniTablineFill = { link = "TabLineFill" },
        MiniTablineHidden = { fg = colors.bg4, bg = colors.bg1, reverse = config.invert_tabline },
        MiniTablineModifiedCurrent = {
            fg = colors.bg1,
            bg = colors.green_bright,
            bold = config.bold,
            reverse = config.invert_tabline,
        },
        MiniTablineModifiedHidden = { fg = colors.bg1, bg = colors.bg4, reverse = config.invert_tabline },
        MiniTablineModifiedVisible = { fg = colors.bg1, bg = colors.fg1, reverse = config.invert_tabline },
        MiniTablineTabpagesection = { link = "Search" },
        MiniTablineVisible = { fg = colors.fg1, bg = colors.bg1, reverse = config.invert_tabline },
        MiniTestEmphasis = { bold = config.bold },
        MiniTestFail = { link = "NightshadeRedBold" },
        MiniTestPass = { link = "NightshadeGreenBold" },
        MiniTrailspace = { bg = colors.red_bright },
        WhichKeyTitle = { link = "NormalFloat" },
        NeoTreeFloatBorder = { link = "NightshadeGray" },
        NeoTreeTitleBar = { fg = colors.fg1, bg = colors.bg2 },
        NeoTreeDirectoryIcon = { link = "NightshadeGreen" },
        NeoTreeDirectoryName = { link = "NightshadeGreenBold" },
        ["@comment"] = { link = "Comment" },
        ["@none"] = { bg = "NONE", fg = "NONE" },
        ["@preproc"] = { link = "PreProc" },
        ["@define"] = { link = "Define" },
        ["@operator"] = { link = "Operator" },
        ["@punctuation.delimiter"] = { link = "Delimiter" },
        ["@punctuation.bracket"] = { link = "Delimiter" },
        ["@punctuation.special"] = { link = "Delimiter" },
        ["@string"] = { link = "String" },
        ["@string.regex"] = { link = "String" },
        ["@string.regexp"] = { link = "String" },
        ["@string.escape"] = { link = "SpecialChar" },
        ["@string.special"] = { link = "SpecialChar" },
        ["@string.special.path"] = { link = "Underlined" },
        ["@string.special.symbol"] = { link = "Identifier" },
        ["@string.special.url"] = { link = "Underlined" },
        ["@character"] = { link = "Character" },
        ["@character.special"] = { link = "SpecialChar" },
        ["@boolean"] = { link = "Boolean" },
        ["@number"] = { link = "Number" },
        ["@number.float"] = { link = "Float" },
        ["@float"] = { link = "Float" },
        ["@function"] = { link = "Function" },
        ["@function.builtin"] = { link = "Special" },
        ["@function.call"] = { link = "Function" },
        ["@function.macro"] = { link = "Macro" },
        ["@function.method"] = { link = "Function" },
        ["@method"] = { link = "Function" },
        ["@method.call"] = { link = "Function" },
        ["@constructor"] = { link = "Special" },
        ["@parameter"] = { link = "Identifier" },
        ["@keyword"] = { link = "Keyword" },
        ["@keyword.conditional"] = { link = "Conditional" },
        ["@keyword.debug"] = { link = "Debug" },
        ["@keyword.directive"] = { link = "PreProc" },
        ["@keyword.directive.define"] = { link = "Define" },
        ["@keyword.exception"] = { link = "Exception" },
        ["@keyword.function"] = { link = "Keyword" },
        ["@keyword.import"] = { link = "Include" },
        ["@keyword.operator"] = { link = "NightshadeRed" },
        ["@keyword.repeat"] = { link = "Repeat" },
        ["@keyword.return"] = { link = "Keyword" },
        ["@keyword.storage"] = { link = "StorageClass" },
        ["@conditional"] = { link = "Conditional" },
        ["@repeat"] = { link = "Repeat" },
        ["@debug"] = { link = "Debug" },
        ["@label"] = { link = "Label" },
        ["@include"] = { link = "Include" },
        ["@exception"] = { link = "Exception" },
        ["@type"] = { link = "Type" },
        ["@type.builtin"] = { link = "Type" },
        ["@type.definition"] = { link = "Typedef" },
        ["@type.qualifier"] = { link = "Type" },
        ["@storageclass"] = { link = "StorageClass" },
        ["@attribute"] = { link = "PreProc" },
        ["@field"] = { link = "Identifier" },
        ["@property"] = { link = "Identifier" },
        ["@variable"] = { link = "NightshadeFg1" },
        ["@variable.builtin"] = { link = "Special" },
        ["@variable.member"] = { link = "Identifier" },
        ["@variable.parameter"] = { link = "Identifier" },
        ["@constant"] = { link = "Constant" },
        ["@constant.builtin"] = { link = "Special" },
        ["@constant.macro"] = { link = "Define" },
        ["@markup"] = { link = "NightshadeFg1" },
        ["@markup.strong"] = { bold = config.bold },
        ["@markup.italic"] = { link = "@text.emphasis" },
        ["@markup.underline"] = { underline = config.underline },
        ["@markup.strikethrough"] = { strikethrough = config.strikethrough },
        ["@markup.heading"] = { link = "Title" },
        ["@markup.raw"] = { link = "String" },
        ["@markup.math"] = { link = "Special" },
        ["@markup.environment"] = { link = "Macro" },
        ["@markup.environment.name"] = { link = "Type" },
        ["@markup.link"] = { link = "Underlined" },
        ["@markup.link.label"] = { link = "SpecialChar" },
        ["@markup.list"] = { link = "Delimiter" },
        ["@markup.list.checked"] = { link = "NightshadeGreen" },
        ["@markup.list.unchecked"] = { link = "NightshadeGray" },
        ["@comment.todo"] = { link = "Todo" },
        ["@comment.note"] = { link = "SpecialComment" },
        ["@comment.warning"] = { link = "WarningMsg" },
        ["@comment.error"] = { link = "ErrorMsg" },
        ["@diff.plus"] = { link = "diffAdded" },
        ["@diff.minus"] = { link = "diffRemoved" },
        ["@diff.delta"] = { link = "diffChanged" },
        ["@module"] = { link = "NightshadeFg1" },
        ["@namespace"] = { link = "NightshadeFg1" },
        ["@symbol"] = { link = "Identifier" },
        ["@text"] = { link = "NightshadeFg1" },
        ["@text.strong"] = { bold = config.bold },
        ["@text.emphasis"] = { italic = config.italic.emphasis },
        ["@text.underline"] = { underline = config.underline },
        ["@text.strike"] = { strikethrough = config.strikethrough },
        ["@text.title"] = { link = "Title" },
        ["@text.literal"] = { link = "String" },
        ["@text.uri"] = { link = "Underlined" },
        ["@text.math"] = { link = "Special" },
        ["@text.environment"] = { link = "Macro" },
        ["@text.environment.name"] = { link = "Type" },
        ["@text.reference"] = { link = "Constant" },
        ["@text.todo"] = { link = "Todo" },
        ["@text.todo.checked"] = { link = "NightshadeGreen" },
        ["@text.todo.unchecked"] = { link = "NightshadeGray" },
        ["@text.note"] = { link = "SpecialComment" },
        ["@text.note.comment"] = { fg = colors.magenta_bright, bold = config.bold },
        ["@text.warning"] = { link = "WarningMsg" },
        ["@text.danger"] = { link = "ErrorMsg" },
        ["@text.danger.comment"] = { fg = colors.fg0, bg = colors.red_bright, bold = config.bold },
        ["@text.diff.add"] = { link = "diffAdded" },
        ["@text.diff.delete"] = { link = "diffRemoved" },
        ["@tag"] = { link = "Tag" },
        ["@tag.attribute"] = { link = "Identifier" },
        ["@tag.delimiter"] = { link = "Delimiter" },
        ["@punctuation"] = { link = "Delimiter" },
        ["@macro"] = { link = "Macro" },
        ["@structure"] = { link = "Structure" },
        ["@lsp.type.class"] = { link = "@type" },
        ["@lsp.type.comment"] = { link = "@comment" },
        ["@lsp.type.decorator"] = { link = "@macro" },
        ["@lsp.type.enum"] = { link = "@type" },
        ["@lsp.type.enumMember"] = { link = "@constant" },
        ["@lsp.type.function"] = { link = "@function" },
        ["@lsp.type.interface"] = { link = "@constructor" },
        ["@lsp.type.macro"] = { link = "@macro" },
        ["@lsp.type.method"] = { link = "@method" },
        ["@lsp.type.modifier.java"] = { link = "@keyword.type.java" },
        ["@lsp.type.namespace"] = { link = "@namespace" },
        ["@lsp.type.parameter"] = { link = "@parameter" },
        ["@lsp.type.property"] = { link = "@property" },
        ["@lsp.type.struct"] = { link = "@type" },
        ["@lsp.type.type"] = { link = "@type" },
        ["@lsp.type.typeParameter"] = { link = "@type.definition" },
        ["@lsp.type.variable"] = { link = "@variable" },

        -- NeoTreeDirectoryName = { link = "Directory" },
        -- NeoTreeDotfile = { fg = colors.fg4 },
        -- NeoTreeFadeText1 = { fg = colors.fg3 },
        -- NeoTreeFadeText2 = { fg = colors.fg4 },
        -- NeoTreeFileIcon = { fg = colors.blue },
        -- NeoTreeFileName = { fg = colors.fg1 },
        -- NeoTreeFileNameOpened = { fg = colors.fg1, bold = true },
        -- NeoTreeFileStats = { fg = colors.fg3 },
        -- NeoTreeFileStatsHeader = { fg = colors.fg2, italic = true },
        -- NeoTreeFilterTerm = { link = "SpecialChar" },
        -- NeoTreeHiddenByName = { link = "NeoTreeDotfile" },
        -- NeoTreeIndentMarker = { fg = colors.fg4 },
        -- NeoTreeMessage = { fg = colors.fg3, italic = true },
        -- NeoTreeModified = { fg = colors.yellow },
        -- NeoTreeRootName = { fg = colors.fg1, bold = true, italic = true },
        -- NeoTreeSymbolicLinkTarget = { link = "NeoTreeFileName" },
        -- NeoTreeExpander = { fg = colors.fg4 },
        -- NeoTreeWindowsHidden = { link = "NeoTreeDotfile" },
        -- NeoTreePreview = { link = "Search" },
        -- NeoTreeGitAdded = { link = "GitGutterAdd" },
        -- NeoTreeGitConflict = { fg = colors.orange, bold = true, italic = true },
        -- NeoTreeGitDeleted = { link = "GitGutterDelete" },
        -- NeoTreeGitIgnored = { link = "NeoTreeDotfile" },
        -- NeoTreeGitModified = { link = "GitGutterChange" },
        -- NeoTreeGitRenamed = { link = "NeoTreeGitModified" },
        -- NeoTreeGitStaged = { link = "NeoTreeGitAdded" },
        -- NeoTreeGitUntracked = { fg = colors.orange, italic = true },
        -- NeoTreeGitUnstaged = { link = "NeoTreeGitConflict" },
        -- NeoTreeTabActive = { fg = colors.fg1, bold = true },
        -- NeoTreeTabInactive = { fg = colors.fg4, bg = colors.bg1 },
        -- NeoTreeTabSeparatorActive = { fg = colors.bg1 },
        -- NeoTreeTabSeparatorInactive = { fg = colors.bg2, bg = colors.bg1 },
    }

    for group, hl in pairs(config.overrides) do
        if groups[group] then
            -- "link" should not mix with other configs (:h hi-link)
            groups[group].link = nil
        end

        groups[group] = vim.tbl_extend("force", groups[group] or {}, hl)
    end

    return groups
end

---@param config NightshadeConfig?
Nightshade.setup = function(config)
    Nightshade.config = vim.deepcopy(default_config)
    Nightshade.config = vim.tbl_deep_extend("force", Nightshade.config, config or {})
end

--- main load function
Nightshade.load = function()
    if vim.version().minor < 8 then
        vim.notify_once("nightshade.nvim: you must use neovim 0.8 or higher")
        return
    end

    -- reset colors
    if vim.g.colors_name then
        vim.cmd.hi("clear")
    end
    vim.g.colors_name = "nightshade"
    vim.o.termguicolors = true

    local groups = get_groups()

    -- add highlights
    for group, settings in pairs(groups) do
        vim.api.nvim_set_hl(0, group, settings)
    end
end

return Nightshade
